-- luacheck config: WoW runs Lua 5.1. Run: luacheck .
std = "lua51"
max_line_length = false
exclude_files = { "Release/" }
-- Style only, used on purpose here: empty if branches holding a comment, an
-- unused self, reusing a name in an inner scope.
ignore = { "542", "212/self", "421", "422", "431" }

-- What the addon defines or changes
globals = {
	"CinematicDB", "SlashCmdList", "StaticPopupDialogs", "ColorPickerFrame",
	"Cinematic_Toggle", "Cinematic_ToggleUI", "Cinematic_StartCam", "Cinematic_Peek", "Cinematic_FlyBy",
	"SLASH_CINEMATIC1", "SLASH_CINEMATIC2",
	"BINDING_HEADER_CINEMATIC",
	"BINDING_NAME_CINEMATIC_TOGGLE", "BINDING_NAME_CINEMATIC_PEEK", "BINDING_NAME_CINEMATIC_HIDEUI",
	"BINDING_NAME_CINEMATIC_FLYBY", "BINDING_NAME_CINEMATIC_CAM_VISTA", "BINDING_NAME_CINEMATIC_CAM_IDLE",
	"BINDING_NAME_CINEMATIC_CAM_FISH", "BINDING_NAME_CINEMATIC_CAM_DEATH", "BINDING_NAME_CINEMATIC_CAM_COZY",
}

-- The WoW API the addon uses (add new ones here as they come up)
read_globals = {
	"AuraUtil",
	"BackdropTemplateMixin",
	"CANCEL",
	"C_AddOns",
	"C_CVar",
	"C_ChatInfo",
	"C_CreatureInfo",
	"C_GossipInfo",
	"C_Item",
	"C_Map",
	"C_Minimap",
	"C_NamePlate",
	"C_PlayerInfo",
	"C_QuestLog",
	"C_Spell",
	"C_Timer",
	"C_UnitAuras",
	"C_Weather",
	"CameraZoomIn",
	"CameraZoomOut",
	"ChatEdit_GetActiveWindow",
	"ChatFontNormal",
	"ChatFrameUtil",
	"ChatFrame_AddMessageEventFilter",
	"ClearOverrideBindings",
	"CreateColor",
	"CreateFrame",
	"DisableAddOn",
	"DoEmote",
	"Enum",
	"GameFontNormalHuge",
	"GameFontNormalLarge",
	"GameTooltip",
	"GameTooltipTextLeft1",
	"GameTooltip_SetDefaultAnchor",
	"GetAddOnInfo",
	"GetAddOnMetadata",
	"GetBindingAction",
	"GetBindingKey",
	"GetBindingText",
	"GetBuildInfo",
	"GetCVar",
	"GetCVarBool",
	"GetCameraZoom",
	"GetChannelList",
	"GetCurrentBindingSet",
	"GetCursorInfo",
	"GetCursorPosition",
	"GetGameTime",
	"GetInventoryItemID",
	"GetItemInfoInstant",
	"GetLocale",
	"GetMouseFoci",
	"GetMouseFocus",
	"GetNumAddOns",
	"GetNumGossipActiveQuests",
	"GetNumGossipAvailableQuests",
	"GetNumQuestLogEntries",
	"GetPlayerFacing",
	"GetQuestLogTitle",
	"GetRealZoneText",
	"GetSheathState",
	"GetSpellInfo",
	"GetSubZoneText",
	"GetTime",
	"GetTrackingTexture",
	"GetUnitSpeed",
	"InCombatLockdown",
	"InterfaceOptionsFrame_OpenToCategory",
	"InterfaceOptions_AddCategory",
	"IsAddOnLoaded",
	"IsAltKeyDown",
	"IsControlKeyDown",
	"IsFalling",
	"IsFlying",
	"IsInGroup",
	"IsInInstance",
	"IsInRaid",
	"IsIndoors",
	"IsMounted",
	"IsMouseButtonDown",
	"IsMouselooking",
	"IsPlayerMoving",
	"IsPlayerSpell",
	"IsResting",
	"IsShiftKeyDown",
	"JumpOrAscendStart",
	"LootFrame",
	"MenuUtil",
	"Minimap",
	"MoveViewDownStart",
	"MoveViewDownStop",
	"MoveViewLeftStart",
	"MoveViewLeftStop",
	"MoveViewUpStart",
	"MoveViewUpStop",
	"NUM_CHAT_WINDOWS",
	"NumTaxiNodes",
	"PlayMusic",
	"PlaySound",
	"RELOADUI",
	"ReloadUI",
	"ResetView",
	"SERVER_MESSAGE_PREFIX",
	"SPELL_FAILED_NOT_FISHABLE",
	"SaveAddOns",
	"SaveBindings",
	"SetBinding",
	"SetCVar",
	"SetOverrideBindingClick",
	"SetUIVisibility",
	"SetView",
	"Settings",
	"SitStandOrDescendStart",
	"StaticPopup_FindVisible",
	"StaticPopup_Show",
	"StopMusic",
	"StopSound",
	"SubZoneTextString",
	"TakeTaxiNode",
	"TaxiNodeGetType",
	"TaxiNodeName",
	"ToggleRun",
	"UIErrorsFrame",
	"UIPanelWindows",
	"UIParent",
	"UISpecialFrames",
	"UnitAffectingCombat",
	"UnitBuff",
	"UnitCanAttack",
	"UnitCastingInfo",
	"UnitChannelInfo",
	"UnitCreatureType",
	"UnitExists",
	"UnitFactionGroup",
	"UnitGUID",
	"UnitHealth",
	"UnitHealthMax",
	"UnitIsAFK",
	"UnitIsDead",
	"UnitIsDeadOrGhost",
	"UnitIsFriend",
	"UnitIsGhost",
	"UnitIsPVP",
	"UnitIsPlayer",
	"UnitIsUnit",
	"UnitName",
	"UnitOnTaxi",
	"UnitPlayerControlled",
	"UnitPosition",
	"UnitPower",
	"UnitPowerMax",
	"UnitPowerType",
	"WOW_PROJECT_ID",
	"WOW_PROJECT_MAINLINE",
	"WorldFrame",
	"ZoneTextFrame",
	"ZoneTextString",
	"date",
	"debugstack",
	"geterrorhandler",
	"hooksecurefunc",
	"issecretvalue",
	"seterrorhandler",
	"tinsert",
}
